# Generated by Django 4.2.11 on 2024-03-23 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingVO",
            fields=[
                (
                    "booking_id",
                    models.AutoField(
                        db_column="booking_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "booking_code",
                    models.CharField(db_column="booking_code", max_length=100),
                ),
                (
                    "booking_name",
                    models.CharField(db_column="booking_name", max_length=250),
                ),
                (
                    "booking_date_created",
                    models.DateTimeField(
                        db_column="booking_date_created",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "booking_date_updated",
                    models.DateTimeField(
                        auto_now=True, db_column="booking_date_updated"
                    ),
                ),
            ],
            options={"db_table": "booking_table",},
        ),
        migrations.CreateModel(
            name="BusesVO",
            fields=[
                (
                    "bus_id",
                    models.AutoField(
                        db_column="bus_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "bus_number",
                    models.CharField(
                        db_column="bus_number", default="", max_length=255
                    ),
                ),
                ("bus_seats", models.IntegerField(db_column="bus_seats", default=100)),
                (
                    "bus_status",
                    models.CharField(
                        choices=[("1", "Active"), ("2", "Inactive")],
                        db_column="bus_status",
                        default=1,
                        max_length=2,
                    ),
                ),
                (
                    "bus_date_created",
                    models.DateTimeField(
                        db_column="bus_date_created", default=django.utils.timezone.now
                    ),
                ),
                (
                    "bus_date_updated",
                    models.DateTimeField(auto_now=True, db_column="bus_date_updated"),
                ),
            ],
            options={"db_table": "buses_table",},
        ),
        migrations.CreateModel(
            name="CategoriesVO",
            fields=[
                (
                    "category_id",
                    models.AutoField(
                        db_column="category_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        db_column="category_name", default="", max_length=255
                    ),
                ),
                (
                    "category_description",
                    models.TextField(
                        db_column="category_description", default="", max_length=255
                    ),
                ),
                (
                    "category_status",
                    models.CharField(
                        choices=[("1", "Active"), ("2", "Inactive")],
                        db_column="category_status",
                        default=1,
                        max_length=2,
                    ),
                ),
                (
                    "category_date_created",
                    models.DateTimeField(
                        db_column="category_date_created",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "category_date_updated",
                    models.DateTimeField(
                        auto_now=True, db_column="category_date_updated"
                    ),
                ),
            ],
            options={"db_table": "categories_table",},
        ),
        migrations.CreateModel(
            name="LocationsVO",
            fields=[
                (
                    "locations_id",
                    models.AutoField(
                        db_column="locations_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "locations_name",
                    models.CharField(
                        db_column="locations_name", default="", max_length=255
                    ),
                ),
                (
                    "locations_date_created",
                    models.DateTimeField(
                        db_column="locations_date_created",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "locations_status",
                    models.CharField(
                        choices=[("1", "Active"), ("2", "Inactive")],
                        db_column="locations_status",
                        default=1,
                        max_length=2,
                    ),
                ),
                (
                    "locations_date_updated",
                    models.DateTimeField(
                        auto_now=True, db_column="locations_date_updated"
                    ),
                ),
            ],
            options={"db_table": "locations_table",},
        ),
        migrations.CreateModel(
            name="LoginVO",
            fields=[
                (
                    "login_id",
                    models.AutoField(
                        db_column="login_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "login_username",
                    models.CharField(
                        db_column="login_username", default="", max_length=200
                    ),
                ),
                (
                    "login_password",
                    models.CharField(
                        db_column="login_password", default="", max_length=200
                    ),
                ),
                (
                    "login_role",
                    models.CharField(db_column="login_role", default="", max_length=10),
                ),
                (
                    "login_status",
                    models.BooleanField(
                        db_column="login_status", default="", max_length=1
                    ),
                ),
            ],
            options={"db_table": "login_table",},
        ),
        migrations.CreateModel(
            name="UserVO",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_firstname",
                    models.CharField(
                        db_column="user_firstname", default="", max_length=200
                    ),
                ),
                (
                    "user_lastname",
                    models.CharField(
                        db_column="user_lastname", default="", max_length=200
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        db_column="user_email", default="", max_length=200
                    ),
                ),
                (
                    "user_password",
                    models.CharField(
                        db_column="user_password", default="", max_length=200
                    ),
                ),
                (
                    "user_login_vo",
                    models.ForeignKey(
                        db_column="user_login_id",
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.loginvo",
                    ),
                ),
            ],
            options={"db_table": "user_table",},
        ),
        migrations.CreateModel(
            name="ScheduleVO",
            fields=[
                (
                    "schedule_id",
                    models.AutoField(
                        db_column="schedule_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "schedule_code",
                    models.CharField(db_column="", default=True, max_length=100),
                ),
                (
                    "trip_scheduled",
                    models.DateTimeField(
                        db_column="trip_scheduled", default=django.utils.timezone.now
                    ),
                ),
                (
                    "schedule_fare",
                    models.FloatField(db_column="schedule_fare", default=0),
                ),
                (
                    "schedule_status",
                    models.CharField(
                        choices=[("1", "Active"), ("2", "Cancelled")],
                        db_column="schedule_status",
                        default=1,
                        max_length=2,
                    ),
                ),
                (
                    "trip_scheduled_date_created",
                    models.DateTimeField(
                        db_column="trip_scheduled_created",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "trip_scheduled_date_updated",
                    models.DateTimeField(
                        auto_now=True, db_column="trip_scheduled_updated"
                    ),
                ),
                (
                    "depart_locations_vo",
                    models.ForeignKey(
                        db_column="depart_locations_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depart_schedules",
                        to="base.locationsvo",
                    ),
                ),
                (
                    "destination_locations_vo",
                    models.ForeignKey(
                        db_column="destination_locations_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_schedules",
                        to="base.locationsvo",
                    ),
                ),
                (
                    "schedule_bus_vo",
                    models.ForeignKey(
                        db_column="schedule_bus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.busesvo",
                    ),
                ),
            ],
            options={"db_table": "schedule_table",},
        ),
        migrations.AddField(
            model_name="busesvo",
            name="bus_category_vo",
            field=models.ForeignKey(
                db_column="bus_category_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.categoriesvo",
            ),
        ),
        migrations.CreateModel(
            name="BookingsVO",
            fields=[
                (
                    "booking_id",
                    models.AutoField(
                        db_column="booking_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "booking_code",
                    models.CharField(db_column="booking_code", max_length=100),
                ),
                (
                    "booking_name",
                    models.CharField(db_column="booking_name", max_length=250),
                ),
                (
                    "booking_seats",
                    models.IntegerField(db_column="booking_seats", default=0),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[("1", "Pending"), ("2", "Paid")],
                        db_column="booking_status",
                        default=1,
                        max_length=2,
                    ),
                ),
                (
                    "booking_date_created",
                    models.DateTimeField(
                        db_column="booking_date_created",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "booking_date_updated",
                    models.DateTimeField(
                        auto_now=True, db_column="booking_date_updated"
                    ),
                ),
                (
                    "booking_schedule_vo",
                    models.ForeignKey(
                        db_column="booking_schedule_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.schedulevo",
                    ),
                ),
            ],
            options={"db_table": "bookings_table",},
        ),
    ]
