# Generated by Django 4.2.11 on 2026-08-31 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="BookingVO",),
    ]
