# Generated by Django 5.2.13 on 2026-09-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_delete_bookingvo"),
    ]

    operations = [
        migrations.RemoveField(model_name="schedulevo", name="schedule_code",),
    ]
