# Generated by Django 5.2.13 on 2026-09-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_repair_bookings_schedule_fk"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE bookings_table
                DROP COLUMN booking_payable;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]