# Generated by Django 5.2.13 on 2026-09-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_legacy_booking_payable"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE bookings_table
                ADD CONSTRAINT bookings_table_booking_schedule_fk
                FOREIGN KEY (booking_schedule_id)
                REFERENCES schedule_table (schedule_id);
            """,
            reverse_sql="""
                ALTER TABLE bookings_table
                DROP FOREIGN KEY bookings_table_booking_schedule_fk;
            """,
        ),
    ]