# Generated by Django 5.2.13 on 2026-09-12 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_widen_booking_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingsvo",
            name="booking_user",
            field=models.ForeignKey(
                blank=True,
                db_column="booking_user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bookingsvo",
            name="booking_status",
            field=models.CharField(
                choices=[("1", "Pending"), ("2", "Paid")],
                db_column="booking_status",
                default="1",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="schedulevo",
            name="schedule_status",
            field=models.CharField(
                choices=[("1", "Active"), ("2", "Cancelled")],
                db_column="schedule_status",
                default="1",
                max_length=2,
            ),
        ),
    ]
