# Generated by Django 5.2.13 on 2026-09-12 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_bookingsvo_booking_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(

            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE bookings_table
                        MODIFY COLUMN booking_user_id integer NOT NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE bookings_table
                        MODIFY COLUMN booking_user_id integer NULL;
                    """,
                ),
            ],

            state_operations=[
                migrations.AlterField(
                    model_name="bookingsvo",
                    name="booking_user",
                    field=models.ForeignKey(
                        db_column="booking_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]