# Generated by Django 4.2.11 on 2026-09-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_bookingsvo_booking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingsvo",
            name="booking_status",
            field=models.CharField(
                choices=[("1", "Pending"), ("2", "Paid"), ("3", "Cancelled")],
                db_column="booking_status",
                default="1",
                max_length=2,
            ),
        ),
    ]
